### ISSUE TITLE
Connect with /movies-app

### ISSUE THREAD

**Issue by himanshuxmehra** [himanshuxmehra/movies-app-frontend-react#1]
Connect with /movies-app

**Comment by sidmadke** [comment]
@himanshuxmehra I want work on this issue

**Comment by himanshuxmehra** [comment]
> @himanshuxmehra I want work on this issue

@sidmadke It's a bit tricky. I have prepared the frontend here, we'll have to create API endpoints in django [here](https://github.com/himanshuxmehra/movies-app) and then configure this repo to work accordingly. 
I am still working on creating those endpoints. 
If you wanna try, sure go ahead.
Let me know where you need help.
